### PR TITLE
Convert Source Sheets to Google Docs :)

### PR DESCRIPTION
**Pull request by pzp1997**
**EDIT 7/12/16 7:28 PM (EDT):**
Added the setup instructions.

**EDIT 7/20/16 7:13 PM (CEST):**
Added step six.

## Setup Instructions

1. Create a new Google Developer project
  1. Go to the [Google Developer Console (GDC) Project Selector](https://console.developers.google.com/projectselector/apis)
  2. Project name doesn't matter
  3. Fill out the rest of the form
  4. Click the blue Create button
1. Create Google OAuth credentials
  1. Go to the [GDC API Manager]( https://console.developers.google.com/apis/credentials)
  2. Click Create credentials (blue button)
  3. Select OAuth client ID from the dropdown
  4. Select the Web application radio button
  5. The name doesn't matter
  6. For testing purposes, enter the following under Authorized JavaScript Origins (if you press tab, another box will appear):
    - `http://localhost:8000`
    - `https://localhost:8000`
    - `http://0.0.0.0:8000`
    - `https://0.0.0.0:8000`
  7. For testing purposes, enter the following under Authorized redirect URIs:
    - `http://localhost:8000/gauth/callback`
    - `https://localhost:8000/gauth/callback`
    - `http://localhost:8000/gauth/callback/`
    - `https://localhost:8000/gauth/callback/`
  8. Press Create
  9. Ignore the popup with your client id and client secret
  10. From the credentials list, press the download button next to the credential you just made.
3. Enable the Google Drive API
  1. Go to the [GDC Drive API Overview]( https://console.developers.google.com/apis/api/drive/overview)
  2. Click the Enable button
4. Move the client_secrets.json into position
  1. At the end of step two, you should have downloaded a file named `client_secret_<some_random_number>-<some_random_hash><some_other_stuff>.json`
  2. Move this file into `/path/to/Sefaria-Project/gauth`
  3. Rename it to `client_secrets.json` (note that secrets is plural-- I messed this up once and it took me half an hour to rectify.)
5. Sync the DB to add the models for gauth
  1. From the command line, run `python manage.py syncdb`
6. Add `/path/to/Sefaria-Project/static` to the `TEMPLATE_DIRS` in your `local_settings.py` file.

### CODE REVIEW

**Comment by blockspeiser** [comment]
@pzp1997 I'm excited to play around with this! On my first try a post to `/api/sheets/32458/export_to_drive` gave a database error `no such table: gauth_credentialsmodel`.

Is there some Django syncdb command we need to add new tables? thanks

**Comment by rneiss** [comment]
From Palmer's directions to me:
Create a new Google Developer project
Go to https://console.developers.google.com/projectselector/apis
Project name doesn't matter
Fill out the rest of the form
Click the blue Create button
Create Google OAuth credentials
Go to the Google Developer Console API Manager: https://console.developers.google.com/apis/credentials
Click Create credentials (blue button)
Select OAuth client ID from the dropdown
Select the Web application radio button
The name doesn't matter
For testing purposes, enter the following under Authorized JavaScript Origins (if you press tab, another box will appear):
http://localhost:8000
https://localhost:8000
http://0.0.0.0:8000
https://0.0.0.0:8000
For testing purposes, enter the following under Authorized redirect URIs:
http://localhost:8000/gauth/callback
https://localhost:8000/gauth/callback
http://localhost:8000/gauth/callback/
https://localhost:8000/gauth/callback/
Press Create
Ignore the popup with your client id and client secret
From the credentials list, press the download button next to the credential you just made.
Enable the Google Drive API
Go to https://console.developers.google.com/apis/api/drive/overview
Click the Enable button
Move the client_secrets.json into position
At the end of step two, you should have downloaded a file named client_secret_<some_random_number>-<some_random_hash><some_other_stuff>.json
Move this file into /path/to/Sefaria-Project/gauth
Rename it to "client_secrets.json" (note that secrets is plural-- I messed this up once and it took me half an hour to rectify.)
Sync the DB to add the models for gauth
From the command line ;), run `python manage.py syncdb`

**Comment by pzp1997** [comment]
@blockspeiser Sorry about that, I suppose I should have included the setup instructions I emailed to Russel in the PR description. Thanks @rneiss for including them in your comment. I'm just going to edit the description and include them there now so that they'll be more visible.

**Comment by blockspeiser** [comment]
@pzp1997 @rneiss thanks! my bad should have realized this depends on a lot of plumbing with Google. I was just eager to see it :)

Should we just be setting up an account for Sefaria as a Google developer for testing and launch?

**Comment by pzp1997** [comment]
@blockspeiser For production, I would advise that you create a Google Developer account for Sefaria. For testing, it doesn't really matter, but being that you're going to need to create the account anyway it is probably best to use it for testing too.

**Comment by pzp1997** [comment]
@rneiss has discovered that I forgot to include one other setup step:

You need to add `/path/to/Sefaria-Project/static` to the `TEMPLATE_DIRS` in your `local_settings.py` file.

Thanks for finding this Russel!

**Comment by rneiss** [comment]
Code is currently merged into the Sefaria-Project codebase on branch `sheets2gdoc`. It's undergoing a bit more testing and will be deployed to dev server soon before merging into master.

**Pull request closed without merging**
