### PR TITLE
Script to add link to Targum Yonatan

### PR DESCRIPTION
**Pull request by EliezerIsrael**
Script to add links for Targum Jonathan.
I think this should work fine - it's a simple copy of the Onkelos script, with the strings changed.

### CODE REVIEW

**Comment by benjaminb10** [comment]
Hi @EliezerIsrael I would like to use Sefaria API to make a responsive website for the "Chné Mikra veE'had Targoum" mitsva of the Parasha of the week.

Does the API provides targoum?

Regards!

**Comment by benjaminb10** [comment]
Great, do you know an easy way to know, given a date, which sections of paracha of the week it will be?

**Comment by nsantacruz** [comment]
try our calendar api

https://www.sefaria.org/api/calendars

**Comment by benjaminb10** [comment]
Thanks.

Using export or using API, is there a way to loop verse by verse of a parasha?

My goal is to create a html page helping the chné-mikra mitsva showing 2 times a verse in hebrew followed by its targoum.

I can export the all parasha, but I would like to get verse by verse in a loop to generate this page.

Any help will be great :)

**Comment by benjaminb10** [comment]
Hi @EliezerIsrael 
The GET request of https://www.sefaria.org/api/calendars?year=2019&month=1&day=2
for today (2 january 2019)
Give me this section: `"url": "Exodus.6.2-9.35"`

Then, the GET request of https://www.sefaria.org/api/texts/Exodus.6.2-9.35
for this section give the the all text of the paracha.

How to have only the "alya" of the day. I mean the section of the Paracha of the week, divided by 7 for the today study.

Regards.

**Comment by edamboritz** [comment]
Hi, if you look at the "alts" section of the api response you can see that it is an array corresponding to the structure of the parasha. You can then do some arithmetic to get the matching text from the text in the response ("he or "text") and calcualte which aliyah is the correct one to show.

**Comment by benjaminb10** [comment]
Hi, is there any more simple way to get the text of all alyas of a week?
Like an array for "richon", "cheni", etc. ?

**Comment by edamboritz** [comment]
Hi, we do not currently have an api call that returns just one Aliyah. So the above procedure is the best way, currently.

**Comment by benjaminb10** [comment]
Thank!
Thus, I haven't understood well the procedure.
For instance could you tell me how do you get the alya from the alts structure here?

https://www.sefaria.org/api/texts/Exodus.6.2-9.35
gives this alts:

```
alts": [
[
null,
{
"he": [
"וארא"
],
"en": [
"Vaera"
],
"whole": true
},
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
{
"he": [
"שני"
],
"en": [
"Second"
]
},
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
{
"he": [
"שלישי"
],
"en": [
"Third"
]
}
],
[
null,
null,
null,
null,
null,
null,
null,
{
"he": [
"רביעי"
],
"en": [
"Fourth"
]
}
],
[
null,
null,
null,
null,
null,
null,
{
"he": [
"חמישי"
],
"en": [
"Fifth"
]
},
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
{
"he": [
"שישי"
],
"en": [
"Sixth"
]
}
],
[
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
{
"he": [
"שביעי"
],
"en": [
"Seventh"
]
```

**Pull request merged**
